name = str(input("Your name? "))
email = str(input("Your e-mail "))
age = int(input("Your age? "))
height = float(input("Your height? "))
is_active = bool(input("Do you want get mail from site Y/N"))
